### ISSUE TITLE
some command not found ?

### ISSUE THREAD

**Issue by swalter972** [franchesoni/s2t#1]
It's working, thanks to your guide ^^

I think I have to install those  commands (I found them for xtodo and xclip). Maybers add this to your guide ?

./stop_and_process_recording.sh: ligne 9: deactivate : commande introuvable
./stop_and_process_recording.sh: ligne 15: xclip : commande introuvable
./stop_and_process_recording.sh: ligne 24: xdotool : commande introuvable

**Comment by swalter972** [comment]
You can dele this dumb issue, buit I don't know how to do it outside an environment

**Comment by franchesoni** [comment]
merci!

the issue was that you were not in the python env right? regarding xclip and xdotool they should be installed before! thanks for your feedback :)
